# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b2dda62b2d3ba1be181098331416580097fc9ed9f7077ba162654563594f821aa247f8cfd925679bda2d658c58ee0cd20606340c9806809b02bea345814b2011

test:
  secret_key_base: 13f8c7373c58ec6460a2d190077452f867c5dd47a7270b44f7a7701e6150e39c723b6a337683a4ddb5cef6614c5f35db5ed8c9348ee1bd463948332da25c3593

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
